package com.iprism.school.utils

object Constants {

    const val BASE_URL = "https://littlepebbles.co.in/schoolappnew/teacher_app/ws/"
    const val IMAGES_URL = "https://littlepebbles.co.in/schoolappnew/"
    const val LOGIN_ENDPOINT = "login"
    const val RESEND_OTP_ENDPOINT = "resend_otp"
    const val CLASS_TEACHER_ENDPOINT = "class_teacher"
    const val ATTENDANCE_ENDPOINT = "attendance"
    const val REFRESH_TOKEN_ENDPOINT = "refresh_token"
    const val EVENTS_ENDPOINT = "events"
    const val CIRCULARS_ENDPOINT = "circulars"
    const val ACTIVE_STUDENTS_ENDPOINT = "fetch_active_students"
    const val INACTIVE_STUDENTS_ENDPOINT = "fetch_inactive_students"
    const val PLANNERS_AND_RESOURCES_ENDPOINT = "planners_resources"
    const val DIARY_ENDPOINT = "diary"
    const val DAYCARE_STATUS_ENDPOINT = "daycare_status"
    const val DAYCARE_PLANS_ENDPOINT = "daycare_categories_students"
    const val ALBUM_COVERS_ENDPOINT = "album_covers"
    const val ALBUMS_GALLERY_ENDPOINT = "albums_gallery"
    const val DAYCARE_ALBUM_COVERS_ENDPOINT = "daycare_album_covers"
    const val DAYCARE_ALBUMS_GALLERY_ENDPOINT = "daycare_albums_gallery"
    const val HOLIDAY_CALENDER_ENDPOINT = "holiday_calendar"
    const val STAFF_ATTENDANCE_ENDPOINT = "staff_attendance"
    const val LEAVE_REQUEST_ENDPOINT = "leave_request"
    const val HOME_PAGE_ENDPOINT = "home_page"
    const val TUTORIALS_ENDPOINT = "help_tutorials"
    const val CONTENT_PAGES_ENDPOINT = "content_pages"
    const val MESSAGES_ENDPOINT = "messages"
    const val DAYCARE_MESSAGES_ENDPOINT = "daycare_messages"
    const val DAYCARE_ATTENDANCE_ENDPOINT = "daycare_attendance"
    const val SCHOOL_SUPPORT_ENDPOINT = "school_support"
    const val TECH_SUPPORT_ENDPOINT = "technical_support"
    const val STUDENT_LEAVE_REQUEST_ENDPOINT = "student_leave_requests"
    const val PROFILE_ENDPOINT = "profile"
    const val TIME_TABLE_ENDPOINT = "time_table"
    const val APP_REVIEW_ENDPOINT = "review"
}
