package com.iprism.school.utils

object Constants {

    const val BASE_URL = "https://littlepebbles.co.in/schoolappnew/teacher_app/ws/"
    const val IMAGES_URL = "https://littlepebbles.co.in/schoolappnew/"
//    const val BASE_URL = "https://lpipreschool.com/schoolapp/api/api/"
//    const val IMAGES_URL = "https://lpipreschool.com/schoolapp/"
    const val LOGIN_ENDPOINT = "login"
    const val RESENDOTP_ENDPOINT = "teacher_resend_otp"
    const val TEACHER_ACCESS = "teacher_view_access_details"
    const val CLASSES = "teacher_view_classes_details"
    const val TEACHER_STUDENTS = "class_taecher_view_students_details"
    const val CLASS_STUDENTSNEW = "class_taecher_view_students_dairy_remarks_details"
    const val DAIRY_UPDATE = "class_taecher_dairy_update_details"
    const val TEACHER_ATTANDANCE_UPDATE = "teacher_updating_attendance"
    const val SCHOOL_STAFF = "school_staff_details"
    const val TEACHERVIEWGROUPS = "teacher_view_groups_details"
    const val TEACHERCREATECALENDER = "teacher_create_calender"
    const val TEACHERCALENDERLIST = "teacher_claender_list"
    const val TEACHERCALENDERDETAILS = "teacher_view_single_claender_details"
    const val CALENDER_DELETE = "teacher_delete_calender"
    const val CALENDER_UPDATE = "teacher_update_calender"
    const val CALENDER_IMG_DELETE = "teacher_delete_calender_attachment"
    const val CALENDER_IMG_UPDATE = "teacher_update_calender_attachment"
    const val CREATE_CONSENT= "teacher_create_consent"
    const val CONSENT_LIST= "teacher_consent_list"
    const val CONSENT_SINGLE_VIEW= "teacher_view_single_consent_details"
    const val CONSENT_UPDATE= "teacher_updating_consent"
    const val CONSENT_DELETE= "teacher_delete_consent"
    const val CONSENT_IMG_UPDATE= "teacher_updating_consent_attachment"
    const val CONSENT_IMG_DELETE= "teacher_delete_consent_attachment"
    const val DAYCAREVIEWLIST= "teacher_view_daycare_details"
    const val CREATENEW_MSG= "teacher_create_new_message"
    const val INBOX_MESSAGES= "teacher_inbox_messages"
    const val INBOX_SINGLE_MESSAGES= "teacher_view_single_inbox_message"
    const val REPLAY_INBOX_MESSAGES= "teacher_reply_to_inbox_message"
    const val MARK_ALL_MESSAGES= "teacher_mark_as_all_read_messages"
    const val MSG_UPDATE= "teacher_inbox_message_read_starred_archived"
    const val SEND_ARCHIVED= "teacher_view_sent_messages"
    const val SINGLEVIEW_MSG= "teacher_view_single_sent_message"

    const val ALLCABS= "view_all_cabs_list"

    const val ABOUT_US= "teacher_view_about_us"
    const val TC= "teacher_view_terms_and_conditions"
    const val PRIVACY= "teacher_view_privacy_policy"

    //new Apis

    const val CLASS_TEACHER_ENDPOINT = "class_teacher"
    const val ATTENDANCE_ENDPOINT = "attendance"
    const val REFRESH_TOKEN_ENDPOINT = "refresh_token"
    const val EVENTS_ENDPOINT = "events"
    const val CIRCULARS_ENDPOINT = "circulars"
    const val ACTIVE_STUDENTS_ENDPOINT = "fetch_active_students"
    const val INACTIVE_STUDENTS_ENDPOINT = "fetch_inactive_students"
    const val PLANNERS_AND_RESOURCES_ENDPOINT = "planners_resources"
    const val DIARY_ENDPOINT = "diary"
    const val DAYCARE_STATUS_ENDPOINT = "daycare_status"
    const val DAYCARE_PLANS_ENDPOINT = "daycare_categories_students"
    const val ALBUM_COVERS_ENDPOINT = "album_covers"
    const val ALBUMS_GALLERY_ENDPOINT = "albums_gallery"
    const val DAYCARE_ALBUM_COVERS_ENDPOINT = "daycare_album_covers"
    const val DAYCARE_ALBUMS_GALLERY_ENDPOINT = "daycare_albums_gallery"
    const val HOLIDAY_CALENDER_ENDPOINT = "holiday_calendar"
    const val STAFF_ATTENDANCE_ENDPOINT = "staff_attendance"
    const val LEAVE_REQUEST_ENDPOINT = "leave_request"
    const val HOME_PAGE_ENDPOINT = "home_page"

}
